name: request_pengui
description: "Request Penguin ported to mobile"
publish_to: 'none'
version: 0.1.5

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  url_launcher: ^6.1.11
  http: ^1.3.0
  web_socket_channel: ^3.0.2 
  flutter_markdown: ^0.7.6+2
  google_fonts: ^6.2.1
  ftpconnect: ^2.0.7
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  

flutter_launcher_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true
  remove_alpha_channel_ios: true
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    # Replace with actual hex code
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 128
  macos:
    generate: true
    image_path: "assets/icon/icon.png"
  launcher_name: "Request PenGUI"