// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSyBRMmPAHw_s8ImR185quqmZrz3rhIj8',
    appId: '1:500227745456:web:9a3b1c5e1b49e38658bd75',
    messagingSenderId: '500227745456',
    projectId: 'request-pengui',
    authDomain: 'request-pengui.firebaseapp.com',
    storageBucket: 'request-pengui.firebasestorage.app',
    measurementId: 'G-5PJJF992TP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYekFN0Gpozp_5ep2HuUM4pUPiYZey1HQ',
    appId: '1:500227745456:android:88acaf9e359242c458bd75',
    messagingSenderId: '500227745456',
    projectId: 'request-pengui',
    storageBucket: 'request-pengui.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRWvnlRTnN1RC2lfe54x3TPHymvZD_I7Q',
    appId: '1:500227745456:ios:bb41fc1621bd2d6858bd75',
    messagingSenderId: '500227745456',
    projectId: 'request-pengui',
    storageBucket: 'request-pengui.firebasestorage.app',
    iosBundleId: 'com.example.requestPengui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRWvnlRTnN1RC2lfe54x3TPHymvZD_I7Q',
    appId: '1:500227745456:ios:bb41fc1621bd2d6858bd75',
    messagingSenderId: '500227745456',
    projectId: 'request-pengui',
    storageBucket: 'request-pengui.firebasestorage.app',
    iosBundleId: 'com.example.requestPengui',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSyBRMmPAHw_s8ImR185quqmZrz3rhIj8',
    appId: '1:500227745456:web:93c3b5e565fb29f258bd75',
    messagingSenderId: '500227745456',
    projectId: 'request-pengui',
    authDomain: 'request-pengui.firebaseapp.com',
    storageBucket: 'request-pengui.firebasestorage.app',
    measurementId: 'G-P6BFCNHW7Y',
  );
}
